version: "3.4"

services:
  api:
    image: wexel/auth:api
    restart: unless-stopped
    networks:
      wexel:
        aliases:
          - auth-api
    environment:
      PORT: ''
      DATABASE_URL: ''
      PRIVATE_KEY_PATH: '/keys/private.pem'
      PUBLIC_KEY_PATH: '/keys/public.pem'
    volumes:
      - /opt/docker/volumes/keys:/keys

  db-init:
    image: wexel/auth:db-init
    restart: 'no'
    networks:
      - wexel
    environment:
      DB_HOST: ''
      DB_NAME: ''
      DB_PASS: ''
      DB_PORT: ''
      DB_USER: ''

  keygen:
    image: wexel/auth:keygen
    restart: 'no'
    environment:
      PASSPHRASE: ''
      PRIVATE_KEY_PATH: '/keys/private.pem'
      PUBLIC_KEY_PATH: '/keys/public.pem'
    volumes:
      - /opt/docker/volumes/keys:/keys

networks:
  wexel:
    external: true
